---
image:
  overlay_dir: overlays
  width: 640
  height: 480
  font: font/rounded-mplus-1c-bold.ttf

  font_size: 42
  margin: 5
  stroke_width: 4.5
  interline_spacing: -5
  icon_size: 75

weather:
  locations_file: locations.yml

