---
image:
  overlay_dir: overlays
  width: 980
  height: 480
  font: font/rounded-mplus-1c-bold.ttf

  font_size: 50
  margin: 5
  stroke_width: 4.5
  interline_spacing: -5
  icon_size: 100

weather:
  locations_file: locations.yml

flickr:
  accuracy: 6 # https://www.flickr.com/services/api/flickr.photos.search.html
  radius: 32 # In km. Max 32.
  photos_threshold: 10 # If less than n photos, search again with broader criteria
  group_id: '1463451@N25' # Project Weather
  licenses: '1,2,4,5,7' # https://www.flickr.com/services/api/flickr.photos.licenses.getInfo.html
