module Ozorotter
  class ImageData
    attr_reader :image, :image_path, :photo, :weather

    def initialize(image: nil, image_path: nil, photo: nil, weather: nil)
      @image = image # Binary image generated by ImageMagick
      @photo = photo # Metadata about the photo (Ozorotter::Photo)
      @weather = weather
      @image_path = image_path # Where the image is saved
    end
  end
end

