module Ozorotter
  class ImageData
    attr_reader :image, :photo

    def initialize(image: nil, photo: nil)
      @image = image # Binary image generated by ImageMagick
      @photo = photo # Metadata about the photo (Ozorotter::Photo)
    end
  end
end

