module Ozorotter
  class ImageData
    attr_reader :image, :photo, :weather

    def initialize(image: nil, photo: nil, weather: nil)
      @image = image # Binary image generated by ImageMagick
      @photo = photo # Metadata about the photo (Ozorotter::Photo)
      @weather = weather
    end
  end
end

